// Generated by gencpp from file racecar_interface/ResetObstacle.msg
// DO NOT EDIT!


#ifndef RACECAR_INTERFACE_MESSAGE_RESETOBSTACLE_H
#define RACECAR_INTERFACE_MESSAGE_RESETOBSTACLE_H

#include <ros/service_traits.h>


#include <racecar_interface/ResetObstacleRequest.h>
#include <racecar_interface/ResetObstacleResponse.h>


namespace racecar_interface
{

struct ResetObstacle
{

typedef ResetObstacleRequest Request;
typedef ResetObstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetObstacle
} // namespace racecar_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::racecar_interface::ResetObstacle > {
  static const char* value()
  {
    return "69bb0bdd6e8b3cda2ae51bcc011a37d3";
  }

  static const char* value(const ::racecar_interface::ResetObstacle&) { return value(); }
};

template<>
struct DataType< ::racecar_interface::ResetObstacle > {
  static const char* value()
  {
    return "racecar_interface/ResetObstacle";
  }

  static const char* value(const ::racecar_interface::ResetObstacle&) { return value(); }
};


// service_traits::MD5Sum< ::racecar_interface::ResetObstacleRequest> should match
// service_traits::MD5Sum< ::racecar_interface::ResetObstacle >
template<>
struct MD5Sum< ::racecar_interface::ResetObstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::racecar_interface::ResetObstacle >::value();
  }
  static const char* value(const ::racecar_interface::ResetObstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::racecar_interface::ResetObstacleRequest> should match
// service_traits::DataType< ::racecar_interface::ResetObstacle >
template<>
struct DataType< ::racecar_interface::ResetObstacleRequest>
{
  static const char* value()
  {
    return DataType< ::racecar_interface::ResetObstacle >::value();
  }
  static const char* value(const ::racecar_interface::ResetObstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::racecar_interface::ResetObstacleResponse> should match
// service_traits::MD5Sum< ::racecar_interface::ResetObstacle >
template<>
struct MD5Sum< ::racecar_interface::ResetObstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::racecar_interface::ResetObstacle >::value();
  }
  static const char* value(const ::racecar_interface::ResetObstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::racecar_interface::ResetObstacleResponse> should match
// service_traits::DataType< ::racecar_interface::ResetObstacle >
template<>
struct DataType< ::racecar_interface::ResetObstacleResponse>
{
  static const char* value()
  {
    return DataType< ::racecar_interface::ResetObstacle >::value();
  }
  static const char* value(const ::racecar_interface::ResetObstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RACECAR_INTERFACE_MESSAGE_RESETOBSTACLE_H
