// Generated by gencpp from file racecar_interface/ResetObstacleRequest.msg
// DO NOT EDIT!


#ifndef RACECAR_INTERFACE_MESSAGE_RESETOBSTACLEREQUEST_H
#define RACECAR_INTERFACE_MESSAGE_RESETOBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace racecar_interface
{
template <class ContainerAllocator>
struct ResetObstacleRequest_
{
  typedef ResetObstacleRequest_<ContainerAllocator> Type;

  ResetObstacleRequest_()
    : n(0)  {
    }
  ResetObstacleRequest_(const ContainerAllocator& _alloc)
    : n(0)  {
  (void)_alloc;
    }



   typedef int32_t _n_type;
  _n_type n;





  typedef boost::shared_ptr< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetObstacleRequest_

typedef ::racecar_interface::ResetObstacleRequest_<std::allocator<void> > ResetObstacleRequest;

typedef boost::shared_ptr< ::racecar_interface::ResetObstacleRequest > ResetObstacleRequestPtr;
typedef boost::shared_ptr< ::racecar_interface::ResetObstacleRequest const> ResetObstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator1> & lhs, const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.n == rhs.n;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator1> & lhs, const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace racecar_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4f9810fd56c5f83f02e5c72cbd356e4";
  }

  static const char* value(const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4f9810fd56c5f83ULL;
  static const uint64_t static_value2 = 0xf02e5c72cbd356e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_interface/ResetObstacleRequest";
  }

  static const char* value(const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 n\n"
;
  }

  static const char* value(const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetObstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_interface::ResetObstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_interface::ResetObstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "n: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_INTERFACE_MESSAGE_RESETOBSTACLEREQUEST_H
