// Generated by gencpp from file racecar_interface/Reset.msg
// DO NOT EDIT!


#ifndef RACECAR_INTERFACE_MESSAGE_RESET_H
#define RACECAR_INTERFACE_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <racecar_interface/ResetRequest.h>
#include <racecar_interface/ResetResponse.h>


namespace racecar_interface
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace racecar_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::racecar_interface::Reset > {
  static const char* value()
  {
    return "4ea516c50b8e2b735013ac031a10cc9d";
  }

  static const char* value(const ::racecar_interface::Reset&) { return value(); }
};

template<>
struct DataType< ::racecar_interface::Reset > {
  static const char* value()
  {
    return "racecar_interface/Reset";
  }

  static const char* value(const ::racecar_interface::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::racecar_interface::ResetRequest> should match
// service_traits::MD5Sum< ::racecar_interface::Reset >
template<>
struct MD5Sum< ::racecar_interface::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::racecar_interface::Reset >::value();
  }
  static const char* value(const ::racecar_interface::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::racecar_interface::ResetRequest> should match
// service_traits::DataType< ::racecar_interface::Reset >
template<>
struct DataType< ::racecar_interface::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::racecar_interface::Reset >::value();
  }
  static const char* value(const ::racecar_interface::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::racecar_interface::ResetResponse> should match
// service_traits::MD5Sum< ::racecar_interface::Reset >
template<>
struct MD5Sum< ::racecar_interface::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::racecar_interface::Reset >::value();
  }
  static const char* value(const ::racecar_interface::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::racecar_interface::ResetResponse> should match
// service_traits::DataType< ::racecar_interface::Reset >
template<>
struct DataType< ::racecar_interface::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::racecar_interface::Reset >::value();
  }
  static const char* value(const ::racecar_interface::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RACECAR_INTERFACE_MESSAGE_RESET_H
